'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { spawn } = require('node:child_process');
(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'atlas-auth-'));
  const vault = path.join(dir, 'vault');
  fs.mkdirSync(path.join(vault, 'notes'), { recursive: true });
  fs.mkdirSync(path.join(vault, 'resources'));
  for (let i = 0; i < 7; i++) fs.mkdirSync(path.join(vault, 'notes', 'Category' + i));
  fs.writeFileSync(path.join(vault, 'notes', 'test.md'), '# Test\nLive local data');
  fs.writeFileSync(path.join(vault, 'notes', 'recent.md'), '# Alpha\nRecent sorting fixture');
  fs.writeFileSync(path.join(vault, 'notes', 'old.md'), '# Zulu\nOld filtering fixture');
  const ago = new Date(Date.now() - 60 * 86400e3);
  fs.utimesSync(path.join(vault, 'notes', 'old.md'), ago, ago);
  fs.writeFileSync(path.join(dir, 'outside.txt'), 'private');
  fs.symlinkSync(path.join(dir, 'outside.txt'), path.join(vault, 'notes', 'escape.md'));
  fs.writeFileSync(path.join(vault, 'secret.txt'), 'private');
  fs.writeFileSync(path.join(vault, 'resources', 'page.html'), '<script>alert(1)</script>');
  const state = path.join(dir, 'state');
  const child = spawn(process.execPath, [path.join(__dirname, 'server.js')], { env: { ...process.env, PORT: '0', ATLAS_PUBLIC_URL: 'https://note.lrwei91.online', ATLAS_VAULT: vault, ATLAS_STATE_DIR: state }, stdio: ['ignore', 'pipe', 'pipe'] });
  let base;
  try {
    base = await new Promise((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Startup timeout')), 10000);
      child.stdout.on('data', data => { const match = String(data).match(/http:\/\/localhost:(\d+)/); if (match) { clearTimeout(timer); resolve('http://localhost:' + match[1]); } });
      child.once('exit', code => { clearTimeout(timer); reject(new Error('Server exited ' + code)); });
    });
    const post = (route, body, cookie, origin = 'https://note.lrwei91.online') => fetch(base + route, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin, ...(cookie ? { Cookie: cookie } : {}) }, body: JSON.stringify(body) });
    for (const route of ['/api/tree', '/api/cards', '/api/search?q=test', '/api/doc?path=test.md', '/files/notes/test.md']) assert.equal((await fetch(base + route)).status, 401);
    assert.equal((await fetch(base + '/', { redirect: 'manual' })).status, 302);
    assert.equal((await fetch(base + '/auth/status')).status, 200);
    const credentials = { username: 'admin', password: 'test-passphrase-123' };
    assert.equal((await post('/auth/setup', credentials)).status, 403);
    credentials.setupToken = fs.readFileSync(path.join(state, 'setup-token'), 'utf8');
    assert.equal((await post('/auth/setup', credentials, '', 'https://attacker.example')).status, 403);
    const setup = await post('/auth/setup', credentials); assert.equal(setup.status, 200);
    const cookie = setup.headers.get('set-cookie').split(';')[0];
    assert.match(setup.headers.get('set-cookie'), /HttpOnly; SameSite=Strict.*; Secure/);
    assert.equal(fs.existsSync(path.join(state, 'setup-token')), false);
    assert.equal(fs.statSync(path.join(state, 'admin.json')).mode & 0o777, 0o600);
    assert.equal(fs.readFileSync(path.join(state, 'admin.json'), 'utf8').includes(credentials.password), false);
    assert.equal((await post('/auth/setup', credentials)).status, 409);
    const get = route => fetch(base + route, { headers: { Cookie: cookie } });
    assert.equal((await fetch(base + '/page-touch.js')).status, 200);
    assert.equal((await fetch(base + '/atlas-ui.css')).status, 200);
    assert.equal((await get('/api/cards')).status, 200);
    for (const endpoint of ['/api/cards', '/api/tree', '/api/doc?path=test.md']) {
      const first = await get(endpoint), tag = first.headers.get('etag');
      assert.ok(tag); assert.equal(first.headers.get('cache-control'), 'private, no-cache'); await first.text();
      const cached = await fetch(base + endpoint, { headers: { Cookie: cookie, 'If-None-Match': tag } });
      assert.equal(cached.status, 304); assert.equal(await cached.text(), ''); assert.equal(cached.headers.get('content-length'), null);
      assert.equal((await fetch(base + endpoint, { headers: { 'If-None-Match': tag } })).status, 401);
    }
    assert.equal((await (await get('/api/cards')).json()).cards.length, 3);
    assert.equal((await get('/api/doc?path=escape.md')).status, 404);
    assert.equal((await get('/api/doc?path=../secret.txt')).status, 404);
    assert.equal((await get('/files/secret.txt')).status, 404);
    const html = await get('/files/resources/page.html'); assert.equal(html.headers.get('content-disposition'), 'attachment');
    fs.writeFileSync(path.join(vault, 'notes', 'test.md'), '# Updated\nFresh data');
    assert.match((await (await get('/api/doc?path=test.md')).json()).content, /Fresh data/);
    const imageName = '测试 空格.png';
    fs.writeFileSync(path.join(vault, 'resources', imageName), Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a1S8AAAAASUVORK5CYII=', 'base64'));
    fs.writeFileSync(path.join(vault, 'resources', 'unrelated.png'), 'private-image');
    fs.writeFileSync(path.join(vault, 'notes', 'test.md'), '---\ntitle: Metadata\ntags:\n  - test\n---\n# Updated\nFresh data\n![[测试 空格.png|300x200]]\n![](../resources/%E6%B5%8B%E8%AF%95%20%E7%A9%BA%E6%A0%BC.png)\n<img src="/files/resources/测试%20空格.png" onerror="alert(1)">');
    const parsed = await (await get('/api/doc?path=test.md')).json();
    assert.equal(parsed.assets[imageName], 'resources/' + imageName);
    assert.equal(Object.keys(parsed.assets).length, 3);
    const { JSDOM } = require('jsdom');
    const rendererDOM = new JSDOM('', { runScripts: 'outside-only' });
    rendererDOM.window.eval(fs.readFileSync(path.join(__dirname, 'public/vendor/marked.min.js'), 'utf8'));
    rendererDOM.window.eval(fs.readFileSync(path.join(__dirname, 'public/reader.js'), 'utf8'));
    const rendered = rendererDOM.window.AtlasReader.render(parsed, {assetUrl: p => '/files/' + p});
    const renderedDOM = new JSDOM(rendered);
    assert.equal(renderedDOM.window.document.querySelectorAll('img[src]').length, 3);
    assert.equal(renderedDOM.window.document.querySelector('img').getAttribute('width'), '300');
    assert.equal(renderedDOM.window.document.querySelector('[onerror]'), null);
    assert.equal(renderedDOM.window.document.body.textContent.includes('Metadata'), false);
    for (const d of [rendererDOM, renderedDOM]) d.window.close();
    const shareEndpoint = '/api/share?path=test.md';
    assert.equal((await fetch(base + shareEndpoint, {method:'POST'})).status, 401);
    assert.equal((await post(shareEndpoint, {}, cookie, 'https://attacker.example')).status, 403);
    const shared = await (await post(shareEndpoint, {}, cookie)).json();
    const sharePath = new URL(shared.url).pathname;
    assert.match(sharePath, /^\/s\/[A-Za-z0-9_-]{22}$/);
    assert.equal((await (await get('/api/cards')).json()).cards.find(c => c.relPath === 'test.md').isShared, true);
    assert.equal((await (await get('/api/cards')).json()).cards.find(c => c.relPath === 'recent.md').isShared, false);
    assert.equal((await fetch(base + sharePath)).status, 200);
    assert.equal((await fetch(base + sharePath + '/doc')).status, 200);
    assert.equal((await fetch(base + sharePath + '/file?path=' + encodeURIComponent('resources/' + imageName))).status, 200);
    for (const asset of ['resources/unrelated.png', 'notes/test.md', '../outside.txt']) {
      assert.equal((await fetch(base + sharePath + '/file?path=' + encodeURIComponent(asset))).status, 404);
    }
    const videoName = '演示 视频.mp4';
    const videoBytes = Buffer.from('0123456789abcdef');
    fs.writeFileSync(path.join(vault, 'resources', videoName), videoBytes);
    fs.writeFileSync(path.join(vault, 'resources', 'unrelated.mp4'), 'private-video');
    fs.appendFileSync(path.join(vault, 'notes', 'test.md'), '\n![[演示 视频.mp4|640]]\n![](../resources/%E6%BC%94%E7%A4%BA%20%E8%A7%86%E9%A2%91.mp4)\n<video autoplay onplay="alert(1)" poster="测试 空格.png"><source src="演示 视频.mp4" type="video/mp4"></video>');
    const mediaDoc = await (await fetch(base + sharePath + '/doc')).json();
    assert.equal(mediaDoc.assets[videoName], 'resources/' + videoName);
    const mediaDOM = new JSDOM('', {runScripts:'outside-only'});
    mediaDOM.window.eval(fs.readFileSync(path.join(__dirname, 'public/vendor/marked.min.js'), 'utf8'));
    mediaDOM.window.eval(fs.readFileSync(path.join(__dirname, 'public/reader.js'), 'utf8'));
    const output = new JSDOM(mediaDOM.window.AtlasReader.render(mediaDoc, {shared:true,assetUrl:p=>sharePath+'/file?path='+encodeURIComponent(p)}));
    const videos = [...output.window.document.querySelectorAll('video')];
    assert.equal(videos.length, 3);
    assert.equal(output.window.document.querySelector('img[src*="mp4"]'), null);
    for (const video of videos) { assert.equal(video.hasAttribute('controls'), true); assert.equal(video.hasAttribute('autoplay'), false); assert.equal(video.hasAttribute('onplay'), false); }
    assert.match(videos[2].querySelector('source').getAttribute('src'), /\/s\/.*\/file\?path=/);
    assert.match(videos[2].getAttribute('poster'), /\/s\/.*\/file\?path=/);
    mediaDOM.window.close(); output.window.close();
    const videoURL = base + sharePath + '/file?path=' + encodeURIComponent('resources/' + videoName);
    const fullVideo = await fetch(videoURL); assert.equal(fullVideo.headers.get('content-type'), 'video/mp4');
    assert.deepEqual(Buffer.from(await fullVideo.arrayBuffer()), videoBytes);
    const ifRange = await fetch(videoURL, { headers: { Range: 'bytes=2-5', 'If-Range': fullVideo.headers.get('etag') } });
    assert.equal(ifRange.status, 200); assert.deepEqual(Buffer.from(await ifRange.arrayBuffer()), videoBytes);
    for (const [range, expected, contentRange] of [['bytes=2-5','2345','bytes 2-5/16'], ['bytes=12-','cdef','bytes 12-15/16'], ['bytes=-4','cdef','bytes 12-15/16']]) {
      const r=await fetch(videoURL, {headers:{Range:range}}); assert.equal(r.status,206); assert.equal(r.headers.get('content-range'),contentRange); assert.equal(await r.text(),expected);
    }
    assert.equal((await fetch(videoURL,{method:'HEAD'})).headers.get('content-length'),'16');
    for (const range of ['bytes=99-100','bytes=5-2','bytes=-0','bytes=','bytes=1-2,4-5']) assert.equal((await fetch(videoURL,{headers:{Range:range}})).status,416);
    assert.equal((await fetch(base + '/files/resources/' + encodeURIComponent(videoName))).status,401);
    assert.equal((await fetch(base + '/files/resources/' + encodeURIComponent(videoName), { headers: { 'If-None-Match': fullVideo.headers.get('etag') } })).status, 401);
    assert.equal((await fetch(base + sharePath + '/file?path=resources/unrelated.mp4')).status,404);
    assert.equal((await fetch(base + '/api/cards')).status, 401);
    assert.equal((await (await post(shareEndpoint, {}, cookie)).json()).url, shared.url);
    assert.equal(fs.statSync(path.join(state, 'shares.json')).mode & 0o777, 0o600);
    fs.writeFileSync(path.join(vault, 'notes', 'test.md'), '---\ntitle: hidden\n---\n# Updated\nFresh share update\n![[测试 空格.png|300]]');
    assert.match((await (await fetch(base + sharePath + '/doc')).json()).content, /Fresh share update/);
    assert.equal((await fetch(base + shareEndpoint, {method:'DELETE', headers:{Cookie:cookie, Origin:'https://note.lrwei91.online'}})).status, 200);
    for (const suffix of ['', '/doc', '/file?path=' + encodeURIComponent('resources/' + imageName)]) assert.equal((await fetch(base + sharePath + suffix, { headers: { 'If-None-Match': fullVideo.headers.get('etag') } })).status, 404);
    assert.equal((await (await get('/api/cards')).json()).cards.find(c => c.relPath === 'test.md').isShared, false);
    const replacement = await (await post(shareEndpoint, {}, cookie)).json();
    assert.notEqual(replacement.url, shared.url);
    // External changes and legacy migrations remain visible through the in-memory index.
    const recordsFile = path.join(state, 'shares.json');
    const records = JSON.parse(fs.readFileSync(recordsFile, 'utf8'));
    const legacy = 'a'.repeat(64);
    records[legacy] = { relPath: 'recent.md', createdAt: new Date().toISOString() };
    fs.writeFileSync(recordsFile, JSON.stringify(records));
    assert.equal((await fetch(base + '/share/' + legacy + '/doc')).status, 200);
    const migrated = await (await get('/api/share?path=recent.md')).json();
    assert.match(new URL(migrated.url).pathname, /^\/s\/[A-Za-z0-9_-]{22}$/);
    assert.equal((await fetch(base + new URL(migrated.url).pathname + '/doc')).status, 200);
    await fetch(base + '/api/share?path=recent.md', { method: 'DELETE', headers: { Cookie: cookie, Origin: 'https://note.lrwei91.online' } });
    assert.equal((await fetch(base + '/share/' + legacy + '/doc')).status, 404);
    assert.equal((await fetch(base + new URL(migrated.url).pathname + '/doc')).status, 404);
    const page = await get('/');
    assert.equal(page.headers.get('content-encoding'), 'gzip');
    const pageTag = page.headers.get('etag'); await page.text();
    const plainPage = await fetch(base + '/', { headers: { Cookie: cookie, 'Accept-Encoding': 'gzip;q=0' } });
    assert.equal(plainPage.headers.get('content-encoding'), null); await plainPage.text();
    const page304 = await fetch(base + '/', { headers: { Cookie: cookie, 'If-None-Match': pageTag } });
    assert.equal(page304.status, 304); assert.equal(page304.headers.get('content-length'), null);
    assert.equal(page304.headers.get('vary'), 'Accept-Encoding');
    assert.equal(await page304.text(), '');
    assert.equal((await fetch(base + '/', { redirect: 'manual', headers: { 'If-None-Match': pageTag } })).status, 302);
    const restored = require('node:child_process').spawnSync(process.execPath, ['-e', "const shares=require('./shares');process.stdout.write(shares.find('test.md') || '')"], {cwd: __dirname, env:{...process.env, ATLAS_STATE_DIR:state}, encoding:'utf8'});
    assert.equal(restored.stdout, new URL(replacement.url).pathname.split('/').pop());
    await new Promise((resolve, reject) => {
      const smoke = spawn(process.execPath, [path.join(__dirname, 'smoke-test.js')], { env: { ...process.env, ATLAS_TEST_URL: base, ATLAS_TEST_COOKIE: cookie }, stdio: ['ignore', 'pipe', 'pipe'] });
      smoke.stdout.on('data', data => process.stdout.write(data));
      smoke.stderr.on('data', data => process.stderr.write(data));
      smoke.once('exit', code => code === 0 ? resolve() : reject(new Error('Rendering smoke test failed')));
    });
    assert.equal((await post('/auth/logout', {}, cookie)).status, 200);
    assert.equal((await get('/api/cards')).status, 401);
    assert.equal((await post('/auth/login', { ...credentials, password: 'wrong' })).status, 401);
    assert.equal((await post('/auth/login', credentials)).status, 200);
    for (let i = 0; i < 10; i++) await post('/auth/login', { ...credentials, password: 'wrong' });
    assert.equal((await post('/auth/login', credentials)).status, 429);
    console.log('PASS: login, setup, session, logout, throttling, private files, traversal, live data, share scope/revocation/persistence, image/video rendering, video byte ranges');
  } finally {
    child.kill();
    await new Promise(resolve => child.once('exit', resolve));
    fs.rmSync(dir, { recursive: true, force: true });
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
